export const list = ["PDF", "EXCEL", "CUSTOM"];

export const groupList = [
  {
    name: "Steve",
    type: "CONTACT",
    code: "001"
  },
  {
    name: "John",
    type: "CONTACT",
    code: "0001"
  },
  {
    name: "SBI Bank",
    type: "BANK_ACCOUNT",
    code: "002"
  },
  {
    name: "hdfc Bank 1",
    type: "BANK_ACCOUNT",
    code: "003"
  },
  {
    name: "hdfc Bank 2",
    type: "BANK_ACCOUNT",
    code: "0003"
  },
  {
    name: "Capital Gain",
    type: "ACCOUNT",
    code: "004"
  },
];

export const groups = [
  {
    name: "BANK_ACCOUNT",
    label: "Bank Accounts",
    collapsible: true,
    collapsed: true,
    icon: "account_balance",
  },
  {
    name: "CONTACT",
    label: "Contacts",
    collapsible: true,
    collapsed: true,
    icon: "person",
  },
  {
    name: "ACCOUNT",
    label: "Custom Accounts",
    collapsible: true,
    collapsed: true,
  },
];

export const accounts = [
  {
    type: "BANK_ACCOUNT",
    name: "Cash on hand",
    _id: "b64c5eb884052bbc0a23de45d533a5b5",
  },
  {
    type: "BANK_ACCOUNT",
    name: "My bank account",
    _id: "b64c5eb884052bbc0a23de45d533b21e",
  },
  {
    type: "BANK_ACCOUNT",
    name: "My credit card",
    _id: "b64c5eb884052bbc0a23de45d533b770",
  },
  {
    type: "CONTACT",
    name: "ADANI POWER LIMITED",
    _id: "20c6b430-a7b6-4dc0-9d7f-9d4fbd68c9d7",
  },
  {
    type: "CONTACT",
    name: "Foreign Contact",
    _id: "666ae117-c5d1-4ec2-ba41-3bd8677a3560",
  },
  {
    type: "CONTACT",
    name: "HISAB TECHNOLOGIES LLP",
    _id: "5ae5b712-b28d-4a33-9868-cf4a0edefea5",
  },
  {
    type: "CONTACT",
    name: "MAHENDRA SINGH DHONI",
    _id: "61ad0a86-3f5f-41be-bfe2-356b12a3eeac",
  },
  {
    type: "CONTACT",
    name: "RELIANCE JIO INFOCOMM LIMITED",

    _id: "e8a1f8a2-f030-4f81-a595-bd36e2ee0688",
  },
  {
    type: "CONTACT",

    name: "Sahil",
    _id: "58a40b9b-641c-469f-bb3b-a76fb7c7fc6a",
  },
  {
    type: "CONTACT",

    name: "Sahil-1",

    _id: "e54ba9aa-0c49-417b-8e21-2c6e108d91b4",
  },
  {
    type: "CONTACT",
    name: "Test 1",
    _id: "5d48525c-70fc-4130-a772-c60c9e121bdd",
  },
  {
    type: "CONTACT",
    name: "hiten",
    _id: "01a99188-deeb-4c6f-8af3-056ca3c26c41",
  },
  {
    type: "ACCOUNT",
    name: "2 wheelers",
    _id: "8220cd0d-236f-4164-9185-74944eb0d631",
  },
  {
    type: "ACCOUNT",
    name: "CGST",
    _id: "CGST",
  },
  {
    type: "ACCOUNT",
    name: "CGST Credit",
    _id: "CGST-CREDIT",
  },
  {
    type: "ACCOUNT",
    name: "Capital accounts",
    _id: "892d4638-7f42-4892-8eab-88ac166930b0",
  },
  {
    type: "ACCOUNT",
    name: "Cars",
    _id: "da2b9346-7ee2-4ec8-898c-2a72b96fa835",
  },
  {
    type: "ACCOUNT",
    name: "Depreciation",
    _id: "6862ea58-2d1b-4692-b39c-96b1a2db6280",
  },
  {
    type: "ACCOUNT",
    name: "Electronic assets",
    _id: "a0002b28-5ada-412b-a2ab-2447747e7660",
  },
  {
    type: "ACCOUNT",
    name: "Equipments",
    _id: "fde2b57a-905c-4dee-89ce-6215d0b73fa7",
  },
  {
    type: "ACCOUNT",
    name: "Equity",
    _id: "7a949df1-baf1-4622-908a-610b6613d8a7",
  },
  {
    type: "ACCOUNT",
    name: "Fixed assets",
    _id: "b84b1a25-7372-4eca-ad9d-632c80673e3c",
  },
  {
    type: "ACCOUNT",
    name: "Forex gain/loss",
    _id: "FOREX_GAIN_LOSS",
  },
  {
    type: "ACCOUNT",
    name: "Furniture",
    _id: "6ff71874-ed9a-49b1-b8c0-a82dc72e53e2",
  },
  {
    type: "ACCOUNT",
    name: "Gain on sale of assets",
    _id: "5e8939e9-6edc-4a3d-aad2-4a5bddee8d62",
  },
  {
    type: "ACCOUNT",
    name: "Gold ornaments",
    _id: "1d7b53c3-121c-4098-a4c4-f9b8750c5275",
  },
  {
    type: "ACCOUNT",
    name: "HDFC life",
    _id: "7b3b9440-db83-410d-8d91-0e627de313fb",
  },
  {
    type: "ACCOUNT",
    name: "IGST",
    _id: "IGST",
  },
  {
    type: "ACCOUNT",
    name: "IGST Credit",
    _id: "IGST-CREDIT",
  },
  {
    type: "ACCOUNT",
    name: "Indirect expense",
    _id: "fa54e553-b664-4265-8da4-fc8f0b2f1056",
  },
  {
    type: "ACCOUNT",
    name: "Indirect income",
    _id: "d471d5c6-157f-43ca-80ef-9a506bc697c1",
  },
  {
    type: "ACCOUNT",
    name: "Interest income",
    _id: "649cbb84-fc03-439b-983f-5e8572f8555c",
  },
  {
    type: "ACCOUNT",
    name: "Interest paid",
    _id: "2bf5580e-7275-4937-9437-facbe7dda24d",
  },
  {
    type: "ACCOUNT",
    name: "Investments",
    _id: "9f93e365-0f49-4626-96c6-7088f753cba8",
  },
  {
    type: "ACCOUNT",
    name: "LIC",
    _id: "0ccc4fc7-35a1-4c0e-bd83-d427bc652410",
  },
  {
    type: "ACCOUNT",
    name: "Life insurance",
    _id: "d20a91d1-8a63-461f-a6e4-96e2e528d866",
  },
  {
    type: "ACCOUNT",
    name: "Loans",
    _id: "86940dd1-99b6-4b01-8810-92a428aeb1f8",
  },
  {
    type: "ACCOUNT",
    name: "Loss on sale of assets",
    _id: "abb18328-2c50-4d73-bfaf-47b3fb6044a2",
  },
  {
    type: "ACCOUNT",
    name: "Max life",
    _id: "a916ab0a-bf80-49ee-9cb7-64e3a00c349d",
  },
  {
    type: "ACCOUNT",
    name: "Movable assets",
    _id: "a420e46e-8d61-4128-8dd0-872f5d292a15",
  },
  {
    type: "ACCOUNT",
    name: "Mutual funds",
    _id: "4b64866b-70bd-4cff-8190-1ee1120aa68d",
  },
  {
    type: "ACCOUNT",
    name: "My resident home",
    _id: "09b3464e-e692-4969-8c00-0e27b6dd89bd",
  },
  {
    type: "ACCOUNT",
    name: "Owner1",
    _id: "17496c4e-3800-4cbf-ab7c-e2c975277e00",
  },
  {
    type: "ACCOUNT",
    name: "Owner2",
    _id: "1ac75c53-fe2f-4970-9193-d8d1544ba0ba",
  },
  {
    type: "ACCOUNT",
    name: "Pali hill flat",
    _id: "1071ec70-2373-41f9-b7d0-c2bde928e84f",
  },
  {
    type: "ACCOUNT",
    name: "Retained earnings",
    _id: "RETAINED-EARNING",
  },
  {
    type: "ACCOUNT",
    name: "Round off",
    _id: "ROUND_OFF",
  },
  {
    type: "ACCOUNT",
    name: "SGST",
    _id: "SGST",
  },
  {
    type: "ACCOUNT",
    name: "SGST Credit",
    _id: "SGST-CREDIT",
  },
  {
    type: "ACCOUNT",
    name: "Secured loans",
    _id: "99e4ae6d-af93-40b1-aca4-216f117734e9",
  },
  {
    type: "ACCOUNT",
    name: "Security deposits",
    _id: "b7148329-d88c-4664-8aec-b94edc1855a6",
  },
  {
    type: "ACCOUNT",
    name: "TCS Payable",
    _id: "TCS-PAYABLE",
  },
  {
    type: "ACCOUNT",
    name: "TCS Receivable",
    _id: "TCS-RECEIVABLE",
  },
  {
    type: "ACCOUNT",
    name: "TDS Payable",
    _id: "TDS-PAYABLE",
  },
  {
    type: "ACCOUNT",
    name: "TDS Receivable",
    _id: "TDS-RECEIVABLE",
  },
  {
    type: "ACCOUNT",
    name: "Tax Credits",
    _id: "TAX-CREDITS",
  },
  {
    type: "ACCOUNT",
    name: "Taxes",
    _id: "TAXES",
  },
  {
    type: "ACCOUNT",
    name: "Unsecured loans",
    _id: "974d6bf8-9f34-4b8f-b299-1f74bcdcf464",
  },
];

export const country_list = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const country_list_with_code = [
  { name: "Afghanistan", code: "AF" },
  { name: "land Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People'S Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];
